version: '3'

services:
  mongo:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - "mongodata:/data/db"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: mongoexample
      MONGO_INITDB_DATABASE: falconapidb
  
  book-api:
    build:
      context: ./
      dockerfile: ./Dockerfile
    ports:
      - '3000:3000'
    volumes:
      - ./:/usr/api
      - ./logs/:/usr/api/logs
    links:
     - mongo      
     
volumes:
  mongodata: